# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]

[conda]

[directory]
truncation_length = 3

[dotnet]
disabled = true

[env_var]
disabled = true

[elm]
symbol = " "

[git_branch]

[git_commit]
disabled = false
commit_hash_length = 4
tag_disabled = false

[git_state]
disabled = true

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
up_to_date = " ✓ "
untracked = " 🤷 "
stashed = " 📦 "
modified = " 📝 "
staged = ' [++\($count\)](green) '
renamed = " 👅 "
deleted = " 🗑 "

[golang]
symbol = "🐹 "

[hostname]

[jobs]

[kubernetes]
symbol = "⎈ "
disabled = true

[line_break]
disabled = false

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[nodejs]
symbol = ""

[package]
symbol = ""

[python]

[ruby]

[rust]
symbol = " "

[sudo]
style = "bold green"
symbol = "🦸🏽‍♂️ "
disabled = false

[time]
disabled = true

[username]
disabled = false

[custom.emoji]
description = "Displays a (pseudo) random emoji for each prompt"
# change the content of the EMOJIS array to your liking and replace the
# number 12 with the number of items in the array, minus one
command = "EMOJIS=(🌈 🍄 🌹 🍌 🍆 🍑 🍔 🍟 🍕 🧀 🪐 🚀 ☄️); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
# if you are on windows, replace "true" with "1"
when = "true"
shell = ["bash", "--noprofile", "--norc"]
format = "$output"