# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Move the directory to the second line
format = """
$all
$custom$sudo $character """



[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[➜](bold red) "

[cmd_duration]

[conda]

[directory]
read_only = " "
truncation_length = 3
format = "[$path]($style)[$read_only]($read_only_style) "

[dotnet]
disabled = true

[env_var]
disabled = true

[elm]
symbol = " "

[git_branch]
symbol = " "

[git_commit]
disabled = false
commit_hash_length = 4
tag_disabled = false

[git_state]
disabled = true

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "

behind = " 😰 "
diverged = " 😵 "

up_to_date = " ✓ "
untracked = " 🤷 "
stashed = " 📦 "

modified = " 📝 "
staged = ' [++\($count\)](green) '
renamed = " 👅 "

deleted = " 🗑 "


[golang]
symbol = "🐹 "


[hostname]
ssh_only = true
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[jobs]
symbol = "+ "
number_threshold = 4
symbol_threshold = 0
disabled = true

[kubernetes]
symbol = "⎈ "
disabled = true

[line_break]
disabled = false

[nix_shell]
disabled = true

[memory_usage]
disabled = true
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
format = 'via [$symbol]($style)'

[nim]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[package]
symbol = ""

[perl]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[ruby]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'

[sudo]
style = "bold green"
symbol = "🦸🏽‍♂️ "
disabled = false

[time]
disabled = true

[username]
disabled = false

[custom.emoji]
description = "Displays a (pseudo) random emoji for each prompt"
# change the content of the EMOJIS array to your liking and replace the
# number 12 with the number of items in the array, minus one
command = "EMOJIS=(🌈 🍄 🌹 🍌 🍆 🍑 🍔 🍟 🍕 🧀 🪐 🚀 ☄️); EMOJI_INDEX=$(( $RANDOM % 12 + 0 )); echo ${EMOJIS[$EMOJI_INDEX]}"
when = "true"
shell = ["bash", "--noprofile", "--norc"]
format = "$output "

