module.exports = {
  brew: [
    'alerter',
    'aom',
    'apr',
    'apr-util',
    'autoconf',
    // https://github.com/wting/autojump
    'autojump',
    'brotli',
    'c-ares',
    'ca-certificates',
    'cairo',
    // Install GNU core utilities (those that come with macOS are outdated)
    // Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    'coreutils',
    'dos2unix',
    // Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
    'findutils',
    'exa',
    'firefoxpwa',
    'fontconfig',
    'freetype',
    'fribidi',
    'gd',
    'gdbm',
    'gdk-pixbuf',
    'gettext',
    'gh',
    'giflib',
    'glib',
    'gmp',
    // Install GNU `sed`, overwriting the built-in `sed`
    // so we can do "sed -i 's/foo/bar/' file" instead of "sed -i '' 's/foo/bar/' file"
    'gnu-sed --with-default-names',
    'go',
    'gobject-introspection',
    'graphite2',
    'graphviz',
    // upgrade grep so we can get things like inverted match (-v)
    'grep --with-default-names',
    // better, more recent grep
    'homebrew/dupes/grep',
    'gts',
    'harfbuzz',
    'icu4c',
    'imath',
    'jasper',
    'jpeg',
'jpeg-xl',
'libavif',
'libffi',
'libnghttp2',
'libpng',
'libpthread-stubs',
'librsvg',
'libtiff',
'libtool',
'libuv',
'libvmaf',
'libx11',
'libxau',
'libxcb',
'libxdmcp',
'libxext',
'libxrender',
'lz4',
'lzo',
'm4',
'mas',
'moreutils',
'mpdecimal',
'ncurses',
'netpbm',
'node',
'openexr',
'openssl@1.1',
'openssl@3',
'pango',
'pcre',
'pixman',
'pkg-config',
'python@3.9',
'readline',
'six',
'sqlite',
'subversion',
'terminal-notifier',
'tree',
'utf8proc',
// better, more recent vim
    'vim --with-client-server --with-override-system-vi',
'watch',
'webp',
// Install wget with IRI support
    'wget --enable-iri'
'xorgproto',
'xz',
'zsh'
],
  cask: [
'adguard',
'appcleaner',
'betterdiscord-installer',
'betterdisplay',
'cardhop',
'cheatsheet',
'cirrus',
'coteditor',
'customshortcuts',
'discord',
'fig',
'figma',
'find-empty-folders',
'firefox',
'github',
'google-chrome',
'grammarly-desktop',
'hyper',
'iina',
'iterm2',
'karabiner-elements',
'lastfm',
'macfuse',
'mimestream',
'no-ip-duc',
'onyx',
'quicklook-csv',
'quicklook-json',
'raycast',
'setapp',
'signal',
'silicon-info',
'silnite',
'spotify',
'suspicious-package',
'telegram',
'veracrypt',
'webpquicklook',
'yt-music',
'zoom'
  ],
  gem: [
  ],
  npm: [
    'antic',
    'buzzphrase',
    'eslint',
    'instant-markdown-d',
    // 'generator-dockerize',
    // 'gulp',
    'npm-check-updates',
    'prettyjson',
    'trash',
    'vtop'
    // ,'yo'
  ],
  mas: [
    //Actions
    '1586435171',
    //Cardpointers
    '1472875808',
    //Controller
    '1198176727',
    //Craft
    '1487937127',
    //Darkroom
    '953286746'
  ],
};