
# tap repositories and their packages

tap homebrew/core
brew alerter
brew aom
brew apr
brew apr-util
brew autoconf
brew autojump
brew berkeley-db
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew coreutils
brew exa
brew firefoxpwa
brew fontconfig
brew freetype
brew fribidi
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew glib
brew gmp
brew go
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew icu4c
brew imath
brew jasper
brew jpeg
brew jpeg-xl
brew libavif
brew libffi
brew libnghttp2
brew libpng
brew libpthread-stubs
brew librsvg
brew libtiff
brew libtool
brew libuv
brew libvmaf
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew lua
brew lz4
brew lzo
brew m4
brew mas
brew mpdecimal
brew ncurses
brew netpbm
brew node
brew openexr
brew openssl@1.1
brew openssl@3
brew pango
brew pcre
brew perl
brew pixman
brew pkg-config
brew python@3.10
brew python@3.9
brew readline
brew ruby
brew six
brew sqlite
brew subversion
brew terminal-notifier
brew utf8proc
brew vim
brew webp
brew xorgproto
brew xz
brew zsh

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-barlow
cask font-barlow-condensed
cask font-barlow-semi-condensed
cask font-fira-code
cask font-fira-code-nerd-font
cask font-fira-mono-nerd-font
cask font-fira-sans
cask font-fira-sans-extra-condensed
cask font-new-york

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask adguard
cask appcleaner
cask betterdiscord-installer
cask betterdisplay
cask cardhop
cask cheatsheet
cask cirrus
cask coteditor
cask customshortcuts
cask discord
cask fig
cask figma
cask find-empty-folders
cask firefox
cask github
cask google-chrome
cask grammarly-desktop
cask hyper
cask iina
cask iterm2
cask karabiner-elements
cask lastfm
cask macfuse
cask mimestream
cask no-ip-duc
cask quicklook-csv
cask quicklook-json
cask raycast
cask setapp
cask signal
cask silicon-info
cask silnite
cask spotify
cask suspicious-package
cask telegram
cask veracrypt
cask webpquicklook
cask yt-music
cask zoom

tap buo/cask-upgrade

tap martido/graph

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1487937127  Craft               (2.2.4)
appstore 553245401   Friendly Streaming  (5.9.21)
