
# tap repositories and their packages

tap homebrew/core
brew abseil
brew aom
brew apr
brew apr-util
brew aribb24
brew autoconf
brew automake
brew bat
brew bison
brew brightness
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew certifi
brew cjson
brew cmake
brew coreutils
brew dav1d
brew dbus
brew eza
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew ghostscript
brew giflib
brew gifsicle
brew git
brew glib
brew glow
brew gmp
brew gnutls
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew harfbuzz
brew highway
brew icu4c
brew imagemagick
brew imath
brew jasper
brew jbig2dec
brew jpeg-turbo
brew jpeg-xl
brew jq
brew jsoncpp
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libde265
brew libevent
brew libffi
brew libgit2
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew liblqr
brew libmicrohttpd
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lz4
brew lzo
brew m4
brew mackup
brew mas
brew mbedtls
brew mpdecimal
brew mpg123
brew ncurses
brew netpbm
brew nettle
brew node
brew oniguruma
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pinentry-mac
brew pixman
brew pkg-config
brew popt
brew portaudio
brew prettier
brew protobuf
brew python@3.10
brew python@3.12
brew python@3.9
brew rav1e
brew readline
brew reattach-to-user-namespace
brew rsync
brew rubberband
brew sdl2
brew sdl2_ttf
brew shared-mime-info
brew six
brew snappy
brew speex
brew spotifyd
brew sqlite
brew srt
brew subversion
brew svt-av1
brew tcl-tk
brew tesseract
brew theora
brew tldr
brew unbound
brew utf8proc
brew webp
brew x264
brew x265
brew xdg-ninja
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yt-dlp
brew zeromq
brew zimg
brew zlib
brew zoxide
brew zsh
brew zsh-autosuggestions
brew zsh-completions
brew zsh-syntax-highlighting
brew zsh-you-should-use
brew zstd

tap homebrew/cask
cask appcleaner
cask applite
cask betterdisplay
cask camo-studio
cask cheatsheet
cask cirrus
cask customshortcuts
cask discord
cask etrecheckpro
cask find-empty-folders
cask fing
cask firefox
cask font-barlow
cask font-barlow-condensed
cask font-barlow-semi-condensed
cask font-fira-code-nerd-font
cask font-fira-sans
cask font-fira-sans-extra-condensed
cask font-new-york
cask font-sf-compact
cask font-sf-mono
cask font-sf-pro
cask github
cask grammarly-desktop
cask iina
cask iterm2
cask jump-desktop-connect
cask karabiner-elements
cask macfuse
cask mediamate
cask megasync
cask onyx
cask raycast
cask rectangle
cask sf-symbols
cask signal
cask silnite
cask spotify
cask suspicious-package
cask symboliclinker
cask telegram-a
cask telegram-desktop
cask veracrypt
cask vlc
cask webpquicklook
cask zoom

tap homebrew/autoupdate

tap homebrew/bundle

tap homebrew/services

tap alienator88/cask
cask pearcleaner

tap buo/cask-upgrade

tap doron-cohen/tap
brew antidot

tap eth-p/software

tap isacikgoz/taps

tap martido/graph

tap rcmdnk/file
brew brew-file

tap teamookla/speedtest

# App Store applications
appstore 1586435171 Actions (3.2.0)
appstore 1290358394 Cardhop (2.2.17)
appstore 1472875808 CardPointers (5.2.3)
appstore 1441250616 Clean Email (3.0.32)
appstore 1447330651 Copilot (4.1.1)
appstore 1024640650 CotEditor (4.8.5)
appstore 953286746 Darkroom (6.7.10)
appstore 6443923358 Detail Studio (4.13.12)
appstore 975937182 Fantastical (3.8.16)
appstore 1615988943 Folder Peek (1.10.4)
appstore 6443796196 FreeScaler (1.0.1)
appstore 553245401 Friendly Streaming (5.9.59)
appstore 1540705431 Hover for Safari (2.7)
appstore 6444667067 Hyperduck (1.1.0)
appstore 1533805339 Keepa - Price Tracker (4.19)
appstore 409183694 Keynote (14.0)
appstore 1661733229 LocalSend (1.14.0)
appstore 1589391989 Mapper (3.0.1)
appstore 1440405750 MusicHarbor (4.8.2)
appstore 905953485 NordVPN (8.20.0)
appstore 409201541 Pages (14.0)
appstore 1472777122 PayPal Honey (16.5.1)
appstore 1444636541 Photomator (3.3.15)
appstore 1160374471 PiPifier (1.3.1)
appstore 1289583905 Pixelmator Pro (3.6.2)
appstore 1459275972 Playlisty for Apple Music (3.14)
appstore 1344679160 Scrobbles for Last.fm (9.3.3)
appstore 1522267256 Shareful (1.10.1)
appstore 1594183810 Shortery (5.5)
appstore 1607635845 Velja (2.0.4)
appstore 899972312 WordService (2.8.3)
