
# tap repositories and their packages

tap homebrew/core
brew aom
brew apr
brew apr-util
brew autoconf
brew automake
brew bat
brew bat-extras
brew bdw-gc
brew berkeley-db
brew bison
brew brightness
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew chruby
brew cjson
brew cmake
brew cmocka
brew coreutils
brew dav1d
brew dbus
brew entr
brew exa
brew ffmpeg
brew firefoxpwa
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew git
brew git-delta
brew glib
brew gmp
brew gnutls
brew gobject-introspection
brew graphite2
brew graphviz
brew gts
brew guile
brew harfbuzz
brew highway
brew icu4c
brew imath
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew lame
brew leptonica
brew libarchive
brew libass
brew libavif
brew libb2
brew libbluray
brew libevent
brew libffi
brew libidn2
brew libmodplug
brew libnghttp2
brew libogg
brew libpng
brew libpthread-stubs
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew libzip
brew little-cms2
brew lua
brew lz4
brew lzo
brew m4
brew macos-trash
brew mas
brew mbedtls
brew mpdecimal
brew mpg123
brew nasm
brew ncurses
brew netpbm
brew nettle
brew node
brew opencore-amr
brew openexr
brew openjpeg
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew perl
brew pixman
brew pkg-config
brew portaudio
brew prettier
brew protobuf
brew python@3.10
brew python@3.9
brew rav1e
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rubberband
brew ruby-install
brew sdl2
brew sdl2_image
brew sdl2_mixer
brew sdl2_ttf
brew shfmt
brew six
brew snappy
brew speex
brew spotify-tui
brew spotifyd
brew sqlite
brew srt
brew subversion
brew tcl-tk
brew tesseract
brew theora
brew tldr
brew tmux
brew unbound
brew utf8proc
brew webp
brew x264
brew x265
brew xerces-c
brew xorgproto
brew xvid
brew xz
brew yt-dlp
brew zeromq
brew zimg
brew zlib
brew zsh
brew zstd

tap homebrew/autoupdate

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-barlow
cask font-barlow-condensed
cask font-barlow-semi-condensed
cask font-fira-code-nerd-font
cask font-fira-sans
cask font-fira-sans-extra-condensed
cask font-new-york
cask font-sf-compact
cask font-sf-mono
cask font-sf-pro

tap homebrew/cask-versions
cask discord-canary

tap homebrew/services

tap homebrew/cask
cask adguard
cask appcleaner
cask betterdiscord-installer
cask betterdisplay
cask camo-studio
cask cheatsheet
cask cirrus
cask customshortcuts
cask discord
cask fig
cask figma
cask find-empty-folders
cask firefox
cask github
cask grammarly-desktop
cask iterm2
cask karabiner-elements
cask macfuse
cask mimestream
cask no-ip-duc
cask obs
cask raycast
cask screens-connect
cask setapp
cask sf-symbols
cask signal
cask sketch
cask spotify
cask suspicious-package
cask syntax-highlight
cask telegram
cask telegram-desktop
cask veracrypt
cask webpquicklook
cask zoom

tap buo/cask-upgrade

tap eth-p/software
brew bat-extras-batdiff
brew bat-extras-batgrep
brew bat-extras-batman
brew bat-extras-batpipe
brew bat-extras-batwatch
brew bat-extras-prettybat

tap isacikgoz/taps

tap martido/graph

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1586435171  Actions                (1.13.1)
appstore 897446215   Canva                  (1.53.0)
appstore 1500855883  CapCut                 (1.1.0)
appstore 1290358394  Cardhop                (2.2.2)
appstore 1472875808  CardPointers           (4.1.1)
appstore 1198176727  Controller             (5.15.4)
appstore 1487937127  Craft                  (2.3.7)
appstore 953286746   Darkroom               (6.1.1)
appstore 516538625   Disk Decipher          (3.17.8)
appstore 975937182   Fantastical            (3.7.2)
appstore 1615988943  Folder Peek            (1.5.1)
appstore 6443796196  FreeScaler             (1.0.1)
appstore 553245401   Friendly Streaming     (5.9.25)
appstore 1462114288  Grammarly for Safari   (9.63)
appstore 1115567069  Health Auto Export     (2.0.5)
appstore 1533805339  Keepa - Price Tracker  (3.99)
appstore 409183694   Keynote                (12.1)
appstore 1589391989  Mapper                 (1.0)
appstore 1440405750  MusicHarbor            (4.5.1)
appstore 905953485   NordVPN                (7.11.2)
appstore 409203825   Numbers                (12.1)
appstore 409201541   Pages                  (12.1)
appstore 1472777122  PayPal Honey           (14.10.2)
appstore 1160374471  PiPifier               (1.3.1)
appstore 1289583905  Pixelmator Pro         (3.0.1)
appstore 1459275972  Playlisty              (2.23)
appstore 1533703891  PocketTube             (12.2.3)
appstore 1519867270  Refined GitHub         (22.10.12)
appstore 1612180624  Screen Mirror          (0.98)
appstore 1344679160  Scrobbles for Last.fm  (8.6.2)
appstore 1522267256  Shareful               (1.7.1)
appstore 897118787   Shazam                 (2.11.0)
appstore 1594183810  Shortery               (2.8)
appstore 1542271266  Silicon Info           (1.0.3)
appstore 1623301585  Specter                (1.4.4)
appstore 1566795636  Stellar                (2.0.6)
appstore 1482454543  Twitter                (9.30)
appstore 1219074514  Vectornator            (4.10.5)
appstore 1607635845  Velja                  (1.11.2)
appstore 1494451650  VN                     (0.14.2)
appstore 899972312   WordService            (2.8.3)
