set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"

set-option -g mouse on
#setw -g mouse-select-window on
#setw -g mouse-select-pane on
#set-window-option -g mode-mouse on

# Copy mode
setw -g mode-keys vi
bind ` copy-mode
unbind [
unbind p
bind p paste-buffer
bind-key -T edit-mode-vi Up send-keys -X history-up
bind-key -T edit-mode-vi Down send-keys -X history-down
unbind-key -T copy-mode-vi Space     ;   bind-key -T copy-mode-vi v send-keys -X begin-selection
unbind-key -T copy-mode-vi Enter     ;   bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
unbind-key -T copy-mode-vi C-v       ;   bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
unbind-key -T copy-mode-vi [         ;   bind-key -T copy-mode-vi [ send-keys -X begin-selection
unbind-key -T copy-mode-vi ]         ;   bind-key -T copy-mode-vi ] send-keys -X copy-selection
bind y run "tmux save-buffer - | reattach-to-user-namespace pbcopy"

setw -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
set -g set-titles-string '#(pwd)'

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+
# new stuff should open with the same path
bind c new-window -c "#{pane_current_path}"
	
	
# Activity
setw -g monitor-activity on
set -g visual-activity off
set -g base-index 1
# Autorename sanely.
setw -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'
# set -g status-interval 1
# set -g -a terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
### COLOUR (Solarized 256)
	
# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-style default
set -g @sidebar-tree-command 'tree'
set -g @sidebar-tree-width '80'
# set -g @sidebar-tree-pager 'less -'
# default window title colors
set-window-option -g window-status-style fg='colour244' #base0
set-window-option -g window-status-style bg='default'
set-window-option -g window-status-style dim
	
# active window title colors
set-window-option -g window-status-current-style fg='colour166' #orange
set-window-option -g window-status-current-style bg='default'
set-window-option -g window-status-current-style bright
	
# pane border
set-option -g pane-border-style fg='colour235' #base02
set-option -g pane-active-border-style fg='colour240' #base01
	
# message text
set-option -g message-style bg='colour235' #base02
set-option -g message-style fg='colour166' #orange
	
# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
set-option -g destroy-unattached on
# clock
set-window-option -g clock-mode-colour colour64 #green

set-window-option -g window-status-bell-style fg=colour235,bg=colour160 #base02, red

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
	
	
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'