github.com:
    user: mahdz
    oauth_token: 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
    git_protocol: ssh
    users:
        mahdz:
            oauth_token: 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
